image: "alpine:latest"

stages:
  - build
  - test

before_script:
  - apk update
  - apk upgrade
  - apk add gcc libc-dev make
  - gcc --version
  - make --version
  - make

test_encode_moby_dick:
  script:
    - ./huffencode tests/inputs/MobyDick.txt tests/MobyDick.txt.huff
    - diff tests/MobyDick.txt.huff tests/outputs/MobyDick.txt.huff
  tags:
    - tmsquill

test_decode_moby_dick:
  script:
    - ./huffdecode tests/outputs/MobyDick.txt.huff tests/MobyDick.txt
    - diff tests/MobyDick.txt tests/inputs/MobyDick.txt
  tags:
    - tmsquill

test_encode_mississippi:
  script:
    - ./huffencode tests/inputs/mississippi.txt tests/mississippi.txt.huff
    - diff tests/mississippi.txt.huff tests/outputs/mississippi.txt.huff
  tags:
    - tmsquill

test_decode_mississippi:
  script:
    - ./huffdecode tests/outputs/mississippi.txt.huff tests/mississippi.txt
    - diff tests/mississippi.txt tests/inputs/mississippi.txt
  tags:
    - tmsquill

test_encode_ralph:
  script:
    - ./huffencode tests/inputs/ralph.bmp tests/ralph.bmp.huff
    - diff tests/ralph.bmp.huff tests/outputs/ralph.bmp.huff
  tags:
    - tmsquill

test_decode_ralph:
  script:
    - ./huffdecode tests/outputs/ralph.bmp.huff tests/ralph.bmp
    - diff tests/ralph.bmp tests/inputs/ralph.bmp
  tags:
    - tmsquill

test_encode_sense:
  script:
    - ./huffencode tests/inputs/sense.html tests/sense.html.huff
    - diff tests/sense.html.huff tests/outputs/sense.html.huff
  tags:
    - tmsquill

test_decode_sense:
  script:
    - ./huffdecode tests/outputs/sense.html.huff tests/sense.html
    - diff tests/sense.html tests/inputs/sense.html
  tags:
    - tmsquill

test_encode_small:
  script:
    - ./huffencode tests/inputs/small.txt tests/small.txt.huff
    - diff tests/small.txt.huff tests/outputs/small.txt.huff
  tags:
    - tmsquill

test_decode_small:
  script:
    - ./huffdecode tests/outputs/small.txt.huff tests/small.txt
    - diff tests/small.txt tests/inputs/small.txt
  tags:
    - tmsquill

test_encode_ugly:
  script:
    - ./huffencode tests/inputs/ugly.txt tests/ugly.txt.huff
    - diff tests/ugly.txt.huff tests/outputs/ugly.txt.huff
  tags:
    - tmsquill

test_decode_ugly:
  script:
    - ./huffdecode tests/outputs/ugly.txt.huff tests/ugly.txt
    - diff tests/ugly.txt tests/inputs/ugly.txt
  tags:
    - tmsquill
