image: "alpine:latest"

stages:
  - build
  - test

before_script:
  - apk update
  - apk upgrade
  - apk add gcc libc-dev make
  - gcc --version
  - make --version
  - make

test_encode_small:
  script:
    - ./huffencode tests/inputs/small.txt tests/small.txt.huff
    - diff tests/small.txt.huff tests/outputs/small.txt.huff
  tags:
    - tmsquill

test_decode_small:
  script:
    - ./huffdecode tests/outputs/small.txt tests/small.txt
    - diff tests/small.txt tests/inputs/small.txt
  tags:
    - tmsquill
