image: "alpine:latest"

stages:
  - test
  - deploy

before_script:
  - apk update
  - apk upgrade
  - apk add curl gcc libc-dev make
  - gcc --version
  - make --version
  - make

test_decode_evil:
  stage: test
  script:
    - ./huffdecode tests/outputs/evil.jpg.huff tests/evil.jpg
  tags:
    - tmsquill

test_encode_moby_dick:
  stage: test
  script:
    - ./huffencode tests/inputs/MobyDick.txt tests/MobyDick.txt.huff > tests/ftable.txt
    - diff tests/MobyDick.txt.huff tests/outputs/MobyDick.txt.huff
    - diff tests/ftable.txt tests/ftables/MobyDickfreq.txt
  tags:
    - tmsquill

test_decode_moby_dick:
  stage: test
  script:
    - ./huffdecode tests/outputs/MobyDick.txt.huff tests/MobyDick.txt
    - diff tests/MobyDick.txt tests/inputs/MobyDick.txt
  tags:
    - tmsquill

test_encode_mississippi:
  stage: test
  script:
    - ./huffencode tests/inputs/mississippi.txt tests/mississippi.txt.huff > tests/ftable.txt
    - diff tests/mississippi.txt.huff tests/outputs/mississippi.txt.huff
    - diff tests/ftable.txt tests/ftables/mississippifreq.txt
  tags:
    - tmsquill

test_decode_mississippi:
  stage: test
  script:
    - ./huffdecode tests/outputs/mississippi.txt.huff tests/mississippi.txt
    - diff tests/mississippi.txt tests/inputs/mississippi.txt
  tags:
    - tmsquill

test_encode_ralph:
  stage: test
  script:
    - ./huffencode tests/inputs/ralph.bmp tests/ralph.bmp.huff > tests/ftable.txt
    - diff tests/ralph.bmp.huff tests/outputs/ralph.bmp.huff
    - diff tests/ftable.txt tests/ftables/ralphfreq.txt
  tags:
    - tmsquill

test_decode_ralph:
  stage: test
  script:
    - ./huffdecode tests/outputs/ralph.bmp.huff tests/ralph.bmp
    - diff tests/ralph.bmp tests/inputs/ralph.bmp
  tags:
    - tmsquill

test_encode_sense:
  stage: test
  script:
    - ./huffencode tests/inputs/sense.html tests/sense.html.huff > tests/ftable.txt
    - diff tests/sense.html.huff tests/outputs/sense.html.huff
    - diff tests/ftable.txt tests/ftables/sensefreq.txt
  tags:
    - tmsquill

test_decode_sense:
  stage: test
  script:
    - ./huffdecode tests/outputs/sense.html.huff tests/sense.html
    - diff tests/sense.html tests/inputs/sense.html
  tags:
    - tmsquill

test_encode_small:
  stage: test
  script:
    - ./huffencode tests/inputs/small.txt tests/small.txt.huff > tests/ftable.txt
    - diff tests/small.txt.huff tests/outputs/small.txt.huff
    - diff tests/ftable.txt tests/ftables/smallfreq.txt
  tags:
    - tmsquill

test_decode_small:
  stage: test
  script:
    - ./huffdecode tests/outputs/small.txt.huff tests/small.txt
    - diff tests/small.txt tests/inputs/small.txt
  tags:
    - tmsquill

test_encode_ugly:
  stage: test
  script:
    - ./huffencode tests/inputs/ugly.txt tests/ugly.txt.huff > tests/ftable.txt
    - diff tests/ugly.txt.huff tests/outputs/ugly.txt.huff
    - diff tests/ftable.txt tests/ftables/uglyfreq.txt
  tags:
    - tmsquill

test_decode_ugly:
  stage: test
  script:
    - ./huffdecode tests/outputs/ugly.txt.huff tests/ugly.txt
    - diff tests/ugly.txt tests/inputs/ugly.txt
  tags:
    - tmsquill

deploy_huffman:
  stage: deploy
  script:
    - echo --header = Content-Type: application/json >> config.txt
    - echo --header = PRIVATE-TOKEN: Vd22zzP2qvzvv-nz6X-C https://gitlab.com/api/v4/projects/tmsquill%2Fhuffman/releases >> config.txt
    - echo --data = { "name": "Huffman $CI_COMMIT_TAG", "tag_name": "$CI_COMMIT_TAG", "description": "Huffman encoding and decoding programs. Written to work with arbitrary data.", "assets": { "links": [{ "name": "Algorithm", "url": "https://en.wikipedia.org/wiki/Huffman_coding" } ] } } >> config.txt
    - echo --request = POST https://gitlab.com/api/v4/projects/tmsquill%2Fhuffman/releases >> config.txt 
    - curl -K config.txt 
  tags:
    - tmsquill
  only:
    - tags

